# Generated by Django 5.1 on 2024-09-02 19:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("todolist", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="todolist",
            name="is_invisible",
            field=models.BooleanField(default=False),
        ),
    ]
