# Generated by Django 5.1 on 2024-09-04 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("todolist", "0002_todolist_is_invisible"),
    ]

    operations = [
        migrations.AlterField(
            model_name="todolist",
            name="text",
            field=models.TextField(),
        ),
    ]
