# Generated by Django 5.1 on 2024-09-04 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("todolist", "0004_alter_todolist_text"),
    ]

    operations = [
        migrations.AlterField(
            model_name="todolist",
            name="text",
            field=models.CharField(max_length=4500),
        ),
    ]
